Minor usability improvement to check-formatting

diff --git a/ci-utils/check-formatting b/ci-utils/check-formatting
--- a/ci-utils/check-formatting
+++ b/ci-utils/check-formatting
@@ -8,26 +8,46 @@ fi
 
 # make sure we have the right versions of the commands
 YAPF_VERSION=$(sed -E -n 's/ *set\(YAPF_VERSION *"([0-9.]*)".*/\1/p' cmake/GaudiProjectConfig.cmake)
-test "$(yapf --version)" = "yapf $YAPF_VERSION"
+if [ "$(yapf --version)" != "yapf $YAPF_VERSION" ] ; then
+  echo "invalid version of yapf: $(yapf --version) ($YAPF_VERSION required)"
+  exit 1
+fi
 
 CLANG_FORMAT_VERSION=$(sed -E -n 's/ *set\(CLANG_FORMAT_VERSION *"([0-9.]*)".*/\1/p' cmake/GaudiProjectConfig.cmake)
-which clang-format-$CLANG_FORMAT_VERSION >/dev/null
+if ! which clang-format-$CLANG_FORMAT_VERSION >/dev/null ; then
+  echo "clang-format-$CLANG_FORMAT_VERSION command not available"
+  exit 1
+fi
 
-git fetch https://gitlab.cern.ch/gaudi/Gaudi.git ${TARGET_BRANCH}
-git diff --name-only --no-renames --diff-filter MA FETCH_HEAD...HEAD | \
+if [ -n "${TARGET_BRANCH:=$1}" ] ; then
+  git fetch https://gitlab.cern.ch/gaudi/Gaudi.git ${TARGET_BRANCH}
+  files_to_check() {
+    git diff --name-only --no-renames --diff-filter MA FETCH_HEAD...HEAD
+  }
+else
+  files_to_check() {
+    git ls-files
+  }
+fi
+
+files_to_check | \
   grep -E '\.(i?[ch](pp|xx|c)?|cc|hh)$' | xargs --no-run-if-empty --max-procs=$(nproc) --max-args=100 clang-format-$CLANG_FORMAT_VERSION -i --style=file || true
-git diff --name-only --no-renames --diff-filter MA FETCH_HEAD...HEAD | \
+files_to_check | \
   grep -E '\.py$' | xargs --no-run-if-empty --max-procs=$(nproc) --max-args=100 yapf -i || true
 
-echo "From: Gitlab CI <noreply@cern.ch>" > apply-formatting.patch
-echo "Date: $(date -R)" >> apply-formatting.patch
-echo "Subject: [PATCH] Fixed formatting" >> apply-formatting.patch
-echo "" >> apply-formatting.patch
-echo "patch generated by ${job_id}" >> apply-formatting.patch
-echo "" >> apply-formatting.patch
-echo "" >> apply-formatting.patch
-git diff >> apply-formatting.patch
-git diff --stat --exit-code || ( cat <<EOF
+if git diff --exit-code --quiet ; then
+  echo "no change"
+else
+  echo "From: Gitlab CI <noreply@cern.ch>" > apply-formatting.patch
+  echo "Date: $(date -R)" >> apply-formatting.patch
+  echo "Subject: [PATCH] Fixed formatting" >> apply-formatting.patch
+  echo "" >> apply-formatting.patch
+  echo "patch generated by ${job_id}" >> apply-formatting.patch
+  echo "" >> apply-formatting.patch
+  echo "" >> apply-formatting.patch
+  git diff >> apply-formatting.patch
+  if [ -n "${CI}" ] ; then
+    cat <<EOF
 =======================================
  You can fix formatting with:
 
@@ -35,4 +55,12 @@ git diff --stat --exit-code || ( cat <<EOF
 
 =======================================
 EOF
-false )
+  else
+    echo "Changes made to files and recorded as 'apply-formatting.patch'."
+    echo "You can commit them with:"
+    echo "  git commit -a -m 'Fixed formatting'"
+    echo "or discard all non staged changes with:"
+    echo "  git checkout ."
+  fi
+  exit 1
+fi
